services:
  movie-svc:
    build: ./movie-service
    container_name: mflix-movie-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://jorge14:admin4@cluster0.asn1o.mongodb.net/sample_mflix

  user-svc:
    build: ./user-service
    container_name: mflix-user-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://jorge14:admin4@cluster0.asn1o.mongodb.net/sample_mflix

  web:
    build: ./frontend
    container_name: mflix-frontend
    ports:
      - "8080:3000"
    environment:
      - PORT=3000